TARGET = innerproc
HEADERS = cJSON.h dictionary.h sqlite3.h jsonrpc-c.h innerproc.h rc4.h ycapic.h ev.h ifaddrs.h
OBJECTS = innerproc.o cJSON.o jsonrpc-c.o rc4.o ifaddrs.o

ACC= ${CC}

ALDFLAGS = ${LDFLAGS}
LIBS= -lev -lm -lsqlite3 -ldl -liniparser -lycapic
#LIBS= -lev -lm -lsqlite3 -ldl -liniparser
#DEBUG= -g
CFLAGS= -Wall -fPIE -pie 
DEFINE= -DSQL -DANDROID
LINK= -L .
INCLUDE= -I .

%.o: %.c $(HEADERS)
	$(ACC) $(DEFINE) $(INCLUDE) $(ALDFLAGS) -c $< -o $@ 

$(TARGET): $(OBJECTS) 
	$(ACC) $(DEBUG) $(DEFINE) $(OBJECTS) iniparser.a libsqlite3.a -o $@ $(LINK) $(INCLUDE) $(LIBS) $(CFLAGS) $(ALDFLAGS)

clean:
	-rm -f $(OBJECTS)
	-rm -f $(TARGET)
