
app_name: 'testModule'
project_name: 'testProject'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: console
      enable: true



http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true



datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: 'mongodb'
    port: 27017
    dbname:
    user:
    password:
    enable: true

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true

message_brokers:
  - name: 'kafka_1'
    class: 'mantis.fundamental.kafka.MessageBroker'
    enable: false
    hosts: 'localhost:9092'
    zookeepers: 'localhost:2181'
    channels:
      - name: 'test'
        group: 'abcdef'  # simple_consumer if group is null
        handler:  'access.kafka.test.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'ctp_contract_tick_queue'
#        handler: 'get_message'
        enable: true
        type: 'queue' # or queue

services:
  - name: 'http'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: false
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
      TEMPLATES_AUTO_RELOAD: true
      DEBUG: true
      SEND_FILE_MAX_AGE_DEFAULT: 0
    http:
#      host : '172.16.109.237'
      host : '127.0.0.1'
      port : 25100
      threaded: false
      debug: true
      websocket: false

    blueprints:
      - package: 'http'
        url: '/'
        name: 'http'
        register: true
        modules:
          - name: 'views'
            url: 'console'
            routes:
              - url: '/'                    # url name
                name: 'index'   # function name
                methods: 'GET'
              - url: '/orders'                    # url name
                name: 'orders'   # function name
                methods: 'GET'
          - name: 'api'
            url: 'api/m/bw/dev'
            routes:
              - url: '/ticket'           # 用户微信登录
                name: 'get_ticket'       #
                methods: 'POST,GET'

              - url: '/user'           # 用户微信登录
                name: 'get_user_info'       #
                methods: 'GET'

              - url: '/user'           # 用户微信登录
                name: 'update_user_info'       #
                methods: 'PUT'

              - url: '/wx/user'           # 微信用户信息
                name: 'update_wxuser_info'       #
                methods: 'POST'

              - url: '/wx/user'           # 微信用户信息
                name: 'get_wxuser_info'       #
                methods: 'GET'

              - url: '/wx/system'           # 微信系统信息
                name: 'update_wxsystem_info'       #
                methods: 'POST'

              - url: '/device'        # 用户添加设备
                name: 'add_device'
                methods: 'POST'

              - url: '/device/password'           # 设备密码找回
                name: 'get_device_password'       #
                methods: 'POST'

              - url: '/device'          # 更新设备信息
                name: 'update_device'
                methods: 'PUT'

              - url: '/device'        # 删除设备
                name: 'remove_device'
                methods: 'DELETE'

              - url: '/device'            # 获取设备详情
                name: 'get_device_info'
                methods: 'GET'




  - name:       'main'
    id:     'location-adapter'
    enable:     true
    class:      'main.MainService'

    fanout:
      - name: 'switch0'
        channels:
#          - 'redis/con/queue'
          - 'redis/concox_device_message/pubsub'
      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'
      - name: 'strategy_logging'
        channels:
          - 'redis/trade.strategy.log/queue'
          - 'redis/trade.strategy.log.pub/pubsub'

    checkProcesses:
      - name: 'innerbox'
        class: 'check_inner_host.CheckProcessInnerBox'
        iptable: 'innerbox.txt'
        wait: 5
        port: 18699

    listen_address:
      external_app:
        - '11.0.0.100/18699'
#        - '11.0.0.3/18699'
#        - '11.0.0.4/18699'
#        - '11.0.0.5/18699'
#        - '11.0.0.6/18699'
      prop_app:
        - '11.0.0.100/18700'
#        - '11.0.0.3/18700'
#        - '11.0.0.4/18700'
#        - '11.0.0.5/18700'
#        - '11.0.0.6/18700'

    stream_push_address:
      server_audio_url: 'rtmp://11.0.0.1:1935/hls/%s'
      outerbox_video_url: 'rtsp://admin:admin@%s:554/stream1'

    service_ports:
      innerbox: 5678

    property_server: '11.0.0.1:18699'
    gatebox_ipaddr: '11.0.0.40'



# qpid-receive -b localhost:5672 -a "mq_test;{create:always,node:{type:queue,durable:true}}"






